# Build Github Action, to run a test build on all targets
# (Linux, Blit, MacOS, Visual Studio) when the project is checked in.
#
# Thanks in large part to the phenomenal examples of DaftFreak.

name: Build

on:
  push:
    branches:
      - '**' # only run on branches
  pull_request:
  release:
    types: [created]

jobs:
  build:
    env:
      RELEASE_FILE: ${{github.event.repository.name}}-${{github.event.release.tag_name}}

    runs-on: ubuntu-latest

    steps:
      # Check out the main repo
      - name: Checkout
        uses: actions/checkout@v2

      # Linux dependencies
      - name: Install Linux deps
        run: sudo apt update && sudo apt install openscad make

      # And then run the build itself
      - name: Build
        shell: bash
        run: make

      # When it's a release, generate tar/zip files of the build
      - name: Create Zip
        if: github.event_name == 'release'
        shell: bash
        run: zip ${{env.RELEASE_FILE}}.zip *.stl README.md LICENSE.md

      # Push the zip file to the release
      - name: Upload zip to release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          asset_path: ${{env.RELEASE_FILE}}.zip
          upload_url: ${{github.event.release.upload_url}}
          asset_name: ${{env.RELEASE_FILE}}.zip
          asset_content_type: application/zip

      # When not a release, create an artifact
      - name: Upload zip to artifacts
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v2
        with:
          name: result.zip
          path: |
            *.stl
            README.md
            LICENSE.md
